const PREFIX = 'native.calendar';

export const CHANGE_MONTH_LEFT_ARROW = `${PREFIX}.CHANGE_MONTH_LEFT_ARROW`;
export const CHANGE_MONTH_RIGHT_ARROW = `${PREFIX}.CHANGE_MONTH_RIGHT_ARROW`;
export const SELECT_DATE_SLOT = `${PREFIX}.SELECT_DATE_SLOT`;
export const CALENDAR_KNOB = `${PREFIX}.CALENDAR_KNOB`;
export const STATIC_HEADER = 'STATIC_HEADER';
